version: "2.0"

services:
  db:
    image: mysql:5
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=seqdb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin

  server:
    build: .
    volumes:
      - .:/opt/app
    ports:
      - 3000:3000
    depends_on:
      - db
    links:
      - db:db

volumes:
  db:
    driver: local

