version: "2.0"

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 1234:8080

  db:
    image: postgres
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - POSTGRES_DB=seqdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  app:
    build: .
    volumes:
      - .:/opt/app
    ports:
      - 3000:3000
      - 8080:8080
    depends_on:
      - db
    links:
      - db:db

volumes:
  db:
    driver: local

